// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9eHBswI-exXApSMxA7lKAQhMPGTtmte4',
    appId: '1:594512783959:web:9f1d25559fde22938d9112',
    messagingSenderId: '594512783959',
    projectId: 'my-cool-proj11',
    authDomain: 'my-cool-proj11.firebaseapp.com',
    storageBucket: 'my-cool-proj11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi_TzpH7B47M6X6mwW7EtQ2x3dd0fsgKw',
    appId: '1:594512783959:android:695ed6bb935863648d9112',
    messagingSenderId: '594512783959',
    projectId: 'my-cool-proj11',
    storageBucket: 'my-cool-proj11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZv4Wr9cVynNg_VMXkhW-2D2NRfkqyIbY',
    appId: '1:594512783959:ios:c68d6917b223c0628d9112',
    messagingSenderId: '594512783959',
    projectId: 'my-cool-proj11',
    storageBucket: 'my-cool-proj11.appspot.com',
    iosBundleId: 'com.example.newFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZv4Wr9cVynNg_VMXkhW-2D2NRfkqyIbY',
    appId: '1:594512783959:ios:c68d6917b223c0628d9112',
    messagingSenderId: '594512783959',
    projectId: 'my-cool-proj11',
    storageBucket: 'my-cool-proj11.appspot.com',
    iosBundleId: 'com.example.newFlutter',
  );
}
